### ISSUE TITLE
Browsersync doesn't seem to work on windows

### ISSUE THREAD

**Issue by Alphapage** [remicass/vscode-exts#11]
Hello,

I try the browsersync extensions from current vscode and insider build too on different projects without success: it always throws `Cannot get` in chrome.
But if I load localhost:3001, then I get browser-sync config page.
I am running browsersync on windows 10 64bits.
It would be great to add _browser-sync start only_ without opening the browser because I want to start from vscode-chrome-debug launcher.

Thank you in advance for your help.

**Comment by jeremyrajan** [comment]
Hi @Alphapage ,

Thanks for pointing out. Yes, I had noticed some hiccups with WIN machines. And also, I can try to add a config, not open the browser on start.

Cheers,
Jeremy

**Comment by Alphapage** [comment]
I found that folderPath starts with `/` : something like `/c:\\...`. I don't know if it is a vscode bug or the extension bug, but if I remove the `/` then all is working as expected.
Adding a config to customize the extension 👍

**Comment by mspanish** [comment]
@Alphapage where can I edit the folderPath?  Thanks in advance!

**Comment by jeremyrajan** [comment]
@Alphapage @mspanish https://github.com/remicass/vscode-exts/pull/12 should resolve the issue. And I have added configuration for opening the browser on start or not.

**Comment by dkeulen** [comment]
Does not work for me.
Just downloaded & installed the latest version of the extension.
getting the same problem as reported on windows.

**Comment by fzhw88** [comment]
The same, vscode x64 win10 version 1.23.0

**Comment by jeremyrajan** [comment]
Hi guys,

Apologies in not publishing a patch. This has been fixed for windows now, please install version `1.1.1`.

Thank you :)

**Comment by mspanish** [comment]
still not working for me in windows 10, I receive the Cannot GET / when I try localhost:3000
